/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * entr.java
 *
 * Created on Feb 29, 2020, 10:55:40 AM
 */

package gaime;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class entr extends javax.swing.JFrame {
ArrayList<String> usernam= new ArrayList<String>();
ArrayList<String> fnam=new ArrayList<String>();
ArrayList <String> lnam= new ArrayList<String>();
    /** Creates new form entr */
    public entr() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtusir = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(17, 0, 0));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 430, 30);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Dimitri", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setText("SUBMIT");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 120, 120, 50);

        jLabel1.setFont(new java.awt.Font("Dimitri Swank", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("USERNAME:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 50, 120, 30);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Dimitri", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("CANCEL");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 120, 120, 50);

        txtusir.setBackground(new java.awt.Color(51, 51, 51));
        txtusir.setFont(new java.awt.Font("Dimitri", 0, 18)); // NOI18N
        txtusir.setForeground(new java.awt.Color(255, 255, 255));
        txtusir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtusir);
        txtusir.setBounds(160, 50, 200, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sign Up / Register");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 80, 210, 20);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/effects/giphyentr.gif"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 430, 190);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 30, 430, 190);

        setSize(new java.awt.Dimension(449, 260));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
        String users= txtusir.getText();
        if(users.equals(usernam.get(0))||equals(usernam.get(1))||equals(usernam.get(2))||equals(usernam.get(3))||equals(usernam.get(4))||equals(usernam.get(5))||equals(usernam.get(6))||equals(usernam.get(7))||equals(usernam.get(8))||equals(usernam.get(9))){
            
            JOptionPane.showMessageDialog(null,"You are  Registered User!");
            lod1 nwa = new lod1();
            nwa.setUpLoading1();
            nwa.setVisible(true);
            this.setVisible(false);

            
        }else{

            JOptionPane.showMessageDialog(null,"You are not Registered User!");
        }
      }catch(Exception e){
           JOptionPane.showMessageDialog(null,"You are not Registered User!");
      }

}//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
reg re = new reg();
re.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      try{
      Font fn=Font.createFont(Font.TRUETYPE_FONT,getClass().getResourceAsStream("DIMITRI.TTF"));
      Font fn1=Font.createFont(Font.TRUETYPE_FONT,getClass().getResourceAsStream("DIMIS__.TTF"));
          fn=fn.deriveFont(Font.PLAIN,24);
          fn1=fn.deriveFont(Font.PLAIN,18);
    jLabel1.setFont(fn);
    jButton1.setFont(fn1);
    jButton2.setFont(fn1);
  }catch(Exception e){

  }
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      new Lbby().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField txtusir;
    // End of variables declaration//GEN-END:variables

}
