/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * lod3.java
 *
 * Created on Mar 3, 2020, 8:46:13 PM
 */

package gaime;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class lod3 extends javax.swing.JFrame implements Runnable {
Thread th;
int s;
    /** Creates new form lod3 */
    public lod3() {
                super("loading");
 

        initComponents();
         th = new Thread((Runnable)this);
        progress.setVisible(false);
        
        
    }
    public void setUpLoading1(){
         setVisible(false);
    th.start();
    }

    public void run(){
stage3 ts = new stage3();
 try{
       for(int i=2; i<200; i++){
           s=s+2;
           int m= progress.getMaximum();
           int v=progress.getValue();
           if(v<m){
               progress.setValue(progress.getValue()+1);
           }else{

ts.show();
               setVisible(false);

           }th.sleep(40);
       }
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dimitri", 1, 48));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STAGE 111");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(60, 20, 290, 60);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(390, 50, 390, 110);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dimitri", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("M u l T I P L I C A T I O N  easy");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 90, 380, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(350, 70, 400, 130);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/effects/jinSN.gif"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 470, 344);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/effects/Animated-GIF-The-King-of-Fighters-98-Japan-2-Stage-Background-Sprites-Wallpaper-KOF-98-Dream-Match-Never-Ends-KOF-98-The-Slugfest-SNK-Neo-Geo-1998.gif"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 4));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 210, 220, 120);
        jPanel1.add(progress);
        progress.setBounds(280, 10, 146, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 350);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-347)/2, 800, 347);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lod3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables

}
