/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * lodcong.java
 *
 * Created on Mar 7, 2020, 5:51:11 PM
 */

package gaime;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class lodcong extends javax.swing.JFrame implements Runnable{
Thread th;
int s;
    /** Creates new form lodcong */
    public lodcong() {
          super("loading");
              
        initComponents();
        progress.setVisible(false);
 th = new Thread((Runnable)this);
    }
public void setUpLoading1(){
         setVisible(false);
    th.start();
    }

    public void run(){
Lbby ts = new Lbby();
 try{
       for(int i=2; i<200; i++){
           s=s+2;
           int m= progress.getMaximum();
           int v=progress.getValue();
           if(v<m){
               progress.setValue(progress.getValue()+1);
           }else{

ts.show();
               setVisible(false);

           }th.sleep(40);
       }
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONGRATULATIONS!! THANK YOU FOR PLAYING");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 360, 510, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/effects/1563760778_97de1383d7cbd3612c0fb52c5fc627d5ac01bee9r1-500-239_hq.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 400);
        getContentPane().add(progress);
        progress.setBounds(110, 90, 146, 14);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-852)/2, (screenSize.height-401)/2, 852, 401);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lodcong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables

}
