/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * reg.java
 *
 * Created on Feb 29, 2020, 10:56:33 AM
 */

package gaime;

import java.awt.Font;
import java.util.ArrayList;

/**
 *
 * @author Admin
 */
public class reg extends javax.swing.JFrame {

    /** Creates new form reg */
    public reg() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtf = new javax.swing.JTextField();
        txtl = new javax.swing.JTextField();
        txtre1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Dimitri", 0, 24));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 340, 140, 40);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Dimitri", 0, 24));
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(380, 340, 160, 40);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("< BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 0, 110, 23);

        jLabel2.setFont(new java.awt.Font("Dimitri Swank", 0, 24));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LASTNAME :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 120, 130, 30);

        jLabel3.setFont(new java.awt.Font("Dimitri Swank", 0, 24));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FIRSTNAME :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 60, 140, 31);

        txtf.setBackground(new java.awt.Color(51, 51, 51));
        txtf.setFont(new java.awt.Font("Dimitri", 0, 18));
        txtf.setForeground(new java.awt.Color(255, 255, 255));
        txtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtf.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtf);
        txtf.setBounds(290, 60, 220, 23);

        txtl.setBackground(new java.awt.Color(51, 51, 51));
        txtl.setFont(new java.awt.Font("Dimitri", 0, 18));
        txtl.setForeground(new java.awt.Color(255, 255, 255));
        txtl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtl.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtl);
        txtl.setBounds(290, 120, 220, 23);

        txtre1.setBackground(new java.awt.Color(51, 51, 51));
        txtre1.setFont(new java.awt.Font("Dimitri", 0, 18));
        txtre1.setForeground(new java.awt.Color(255, 255, 204));
        txtre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtre1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtre1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtre1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtre1);
        txtre1.setBounds(300, 240, 220, 23);

        jLabel5.setFont(new java.awt.Font("Dimitri Swank", 0, 24));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ENTER USERNAME :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 240, 210, 31);

        jLabel1.setFont(new java.awt.Font("Dimitri Swank", 0, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Avatar Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 190, 490, 120);

        jLabel6.setFont(new java.awt.Font("Dimitri Swank", 0, 24));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 41, 490, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/effects/giphyreg.gif"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 680, 410);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 410);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-700)/2, (screenSize.height-445)/2, 700, 445);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       entr ent = new entr();
        String regs =txtre1.getText();
        
        ent.usernam.add(regs);
        ent.fnam.add(txtf.getText());
        ent.lnam.add(txtl.getText());
        ent.setVisible(true);
        this.hide();
       
}//GEN-LAST:event_jButton1ActionPerformed

    private void txtre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtre1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtre1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
entr ent = new entr();
ent.show();
this.hide();
}//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     try{
      Font fn=Font.createFont(Font.TRUETYPE_FONT,getClass().getResourceAsStream("DIMIS__.TTF"));
      Font fn1=Font.createFont(Font.TRUETYPE_FONT,getClass().getResourceAsStream("DIMITRI.TTF"));
          fn=fn.deriveFont(Font.PLAIN,24);
          fn1=fn.deriveFont(Font.PLAIN,24);
    jLabel2.setFont(fn);
    jLabel3.setFont(fn);
    jLabel5.setFont(fn);
     jButton1.setFont(fn1);
    jButton2.setFont(fn1);
  }catch(Exception e){

  }
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new entr().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtf;
    public static javax.swing.JTextField txtl;
    public static javax.swing.JTextField txtre1;
    // End of variables declaration//GEN-END:variables

}
